title: Cerita Dewasa Terbaru | Peluk Janda
description: Berbagi cerita dewasa untuk kalangan terbatas.
baseurl: "/pelukjanda/pelukjanda.github.io" # Penting jika ini adalah subdirektori di GitHub Pages
url: "https://pelukjanda.github.io"
