name: Sync Blogger to GitHub Pages

on:
  schedule:
    - cron: '0 * * * *'  # Setiap jam
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch & Generate Blog
        env:
          BLOGGER_API_KEY: ${{ secrets.BLOGGER_API_KEY }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
        run: python fetch_blogger.py

      - name: Commit & Push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "✅ Tidak ada perubahan"
          else
            git commit -m "🔄 Update artikel otomatis dari Blogger"
            git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main
          fi
